// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";
import ServiceWorkerRegistration from "@/components/ServiceWorkerRegistration";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Viva Radiante - App de Longevidade Feminina",
  description: "Seu app de longevidade e bem-estar feminino. Rotinas personalizadas com IA, acompanhamento inteligente e conteúdo especializado para você se sentir mais confiante, saudável e radiante.",
  keywords: ["longevidade", "bem-estar", "saúde feminina", "rotinas", "IA", "skincare", "fitness"],
  authors: [{ name: "Viva Radiante" }],
  creator: "Viva Radiante",
  publisher: "Viva Radiante",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL('https://viva-radiante.app'),
  alternates: {
    canonical: '/',
  },
  openGraph: {
    title: "Viva Radiante - App de Longevidade Feminina",
    description: "Seu app de longevidade e bem-estar feminino. Rotinas personalizadas com IA, acompanhamento inteligente e conteúdo especializado.",
    url: "https://viva-radiante.app",
    siteName: "Viva Radiante",
    images: [
      {
        url: "/og-image.png",
        width: 1200,
        height: 630,
        alt: "Viva Radiante - App de Longevidade Feminina",
      },
    ],
    locale: "pt_BR",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Viva Radiante - App de Longevidade Feminina",
    description: "Seu app de longevidade e bem-estar feminino. Rotinas personalizadas com IA, acompanhamento inteligente e conteúdo especializado.",
    images: ["/og-image.png"],
    creator: "@vivaradiante",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  manifest: "/manifest.json",
  icons: {
    icon: "/icon.svg",
    shortcut: "/icon.svg",
    apple: "/icon.svg",
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "Viva Radiante",
    startupImage: [
      {
        url: "/icon.svg",
        media: "(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2)",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
        <meta name="theme-color" content="#ec4899" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="Viva Radiante" />
        <link rel="apple-touch-icon" href="/icon.svg" />
        <link rel="manifest" href="/manifest.json" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
        <ServiceWorkerRegistration />
      </body>
    </html>
  );
}